### ISSUE TITLE
BUG: saving an action with a success event-callback doesn't correctly add the code

### ISSUE THREAD

**Issue by ppi-buck** [dpfaffenbauer/WorkflowGUI#10]
Hey Dominik,

just found a bug in your extension.
When you save an action that has a success-callback configured inside the GUI it produces wrong code in the corresponding file.

**GUI** before saving
![image](https://user-images.githubusercontent.com/37330764/41646304-b1fcbefc-7473-11e8-8388-8ed775232681.png)

**Code**
![image](https://user-images.githubusercontent.com/37330764/41646325-c1057286-7473-11e8-9208-da50573b465c.png)

Which in the **GUI** results to after a reload
![image](https://user-images.githubusercontent.com/37330764/41646365-dcd2437c-7473-11e8-9716-d822b27dc98b.png)

If I remove the first line in the [events][success] - Array it works just fine.

Thanks for providing this extension anyways! It makes understanding and setting up workflows much much easier!

Cheers,
Basti

**Comment by dpfaffenbauer** [comment]
Can you provide a PR for that?

**Comment by ppi-buck** [comment]
Don't think so, wasn't able to find the code where it does this. 

It also seems to only break if I change something in the allowed users for the given action. If I leave everything as is with the configured users the success-callback portion of the code looks fine.

**Comment by ppi-buck** [comment]
I just found out that the wrong markup actually is generated when clicking the "Edit" button for an action (each time adds another wrong row with `success` in it).

As long as you don't save afterwards it still works.
Maybe this will help tracking it down.

**Comment by dpfaffenbauer** [comment]
ok. not sure when I have to time to sort that. I am currently very busy and don't use Pimcore Workflow anymore, so this has a very low priority for me. (unfortunately for you)

**Comment by ppi-buck** [comment]
Do you use something else to edit your workflows? Or just in plain code?

_If the PR suits your needs you can afterwards close this. Thanks for this extension!_
