### ISSUE TITLE
New feature: preconfigured custom report or dedicated panel

### ISSUE THREAD

**Issue by Yivan** [dpfaffenbauer/WorkflowGUI#2]
I found that using custom report we can list state/status, filter them (drilldown rocks for this!) and make workflow even more interesting as we can filter object by state/status.
It is just an idea, but maybe such custom report could be automaticaly configured by the plugin ?

Here is an example (just for objects and not totally optimized, just to get the idea)

![customreportcreation](https://cloud.githubusercontent.com/assets/9025839/22170759/81fcd99e-df82-11e6-99f1-2ac8a0b76dc2.png)

![customreport](https://cloud.githubusercontent.com/assets/9025839/22170764/87663bc8-df82-11e6-9a08-daa84c8a0874.png)

If using native Pimcore custom report is not the "good" way, maybe a dedicated panel "Workflow report" could be added to the plugin.

By the way, "state" are not displayed anywhere ? (status are on the object toolbar). Maybe I will ask or make a PR on Pimcore for this.

**Comment by dpfaffenbauer** [comment]
PR is very much welcome. I personally have no motivation in doing this. The workflow GUI was meant to be merged into Pimcore, just that we don't lose these awesome thing, I created a plugin.

But, as already said, PR is very much welcome.

**Comment by Yivan** [comment]
@dpfaffenbauer Yes, i just checked the Pimcore github repository for the issue asking merging the plugin.
I think too it would be a nice addition in the core, but as they said, they prefer to keep it simple and have no other GUI to handle in the core. I understand this too : ) (like the Custom views wich had before a GUI and now are only PHP configuration).
So I think my idea is not good, as it will involve some code not tightly coupled to the workflow. What i like about your plugin is nothing is changed in database, it is pure only GUI for reading/generating the configuration file.
So better to keep it like this finally i think.

I think the idea of custom report could be added in the Pimcore core documentation in the workflow section.

I just made a PR request on Pimcore adding a documentation page for creating a custom report for workflows. I added another page mentionning your plugin as I think it is really great! Feel free to change my PR if needed, please see:
https://github.com/pimcore/pimcore/pull/1208
**The exact file concerning your plugin is:**
https://github.com/Yivan/pimcore/blob/a307b283243eaa35b6413b8f8c9b2ed050efb647/docs/Development_Documentation/07_Workflow_Management/05_Workflow_Gui.md

Thanks.

**Comment by dpfaffenbauer** [comment]
good :)
