### ISSUE TITLE
Add role selection for Users and Notification Users.

### ISSUE THREAD

**Issue by Yivan** [dpfaffenbauer/WorkflowGUI#3]
Workflow support role attribution, it would be nice if it could be done from the GUI too.
(see: https://github.com/pimcore/pimcore/blob/master/website_example/config/workflowmanagement.example.php#L92)

**Comment by dpfaffenbauer** [comment]
fixed with 02a40c02b0abc88de7083ac761c35eef99520a37

**Comment by Yivan** [comment]
Great, thanks a lot!
