### ISSUE TITLE
Transistion is broken.

### ISSUE THREAD

**Issue by Yivan** [dpfaffenbauer/WorkflowGUI#6]
In the last version of the plugin, transition is broken.
Generated workflow php config use strange name instead of status name.

```
        "transitionDefinitions" => [
            "globalActions" => [

            ],
            "PimcoreWorkflowTranstionDefinitionsTo-3" => [
                "validActions" => [
                    "valider_info_initiales" => NULL
                ]
            ],
            "PimcoreWorkflowTranstionDefinitionsTo-4" => [
                "validActions" => [
                    "valider_media" => NULL
                ]
            ]
        ],
```

`PimcoreWorkflowTranstionDefinitionsTo-3` and `PimcoreWorkflowTranstionDefinitionsTo-4` are not configured status. I need to replace them manually by ("initial" and "media" in my use case).

If it can help, here is the generated config php file (this is the same than the bug on action edition):
[workflowmanagement.zip](https://github.com/dpfaffenbauer/pimcore-WorkflowGUI/files/740797/workflowmanagement.zip)

Thanks.

**Comment by dpfaffenbauer** [comment]
many thanks for testing :)

**Comment by Yivan** [comment]
I just tested this one and it works fine, thanks again!
