### ISSUE TITLE
Pimcore 5 Migration

### ISSUE THREAD

**Issue by fashxp** [dpfaffenbauer/WorkflowGUI#7]
Hi, are there any plans to migrate this plugin to Pimcore 5?

**Comment by dpfaffenbauer** [comment]
Yes there are. Didn't had time yet.

**Comment by fashxp** [comment]
👍  since there is a link to this plugin in Pimcore docs we would love to see it as soon as possible after the release of Pimcore 5 next week. 
Can we help somehow?

**Comment by dpfaffenbauer** [comment]
I am already on it, some people already asked for it ;)

Thanks anyway

**Comment by fashxp** [comment]
shouldn't be too complicated. it is an important extension indeed :-) 
let us know if we can to anything...

**Comment by dpfaffenbauer** [comment]
done, can you test please? 

```composer require dpfaffenbauer/workflow-gui:2.0.x-dev@dev```

**Comment by dpfaffenbauer** [comment]
if you are happy, I can create a release for 2.0 and we are then ready for Pimcore 5 :)

**Comment by fashxp** [comment]
looks good! 
only issue: after creating a new workflow, setting up states, statuses and actions without saving it, creating transition definitions was not possible. 
solution was to save the workflow, close it, open it again and then I could create transition definitions.

**Comment by dpfaffenbauer** [comment]
@fashxp should be fixed with 637653c061449da2fdea2da759565432977100fc, can you confirm please?

**Comment by fashxp** [comment]
confirmed ... works now!

**Comment by dpfaffenbauer** [comment]
awesome :) 👍

**Comment by fashxp** [comment]
thank you very much!! so we are ready for next week ;-)

**Comment by dpfaffenbauer** [comment]
🍻  yeah :)
