### ISSUE TITLE
Failed to install in PIMCORE 5

### ISSUE THREAD

**Issue by kiky-salt** [dpfaffenbauer/WorkflowGUI#9]
Hi @dpfaffenbauer ,

I'm trying install it using composer, and already enable it on the admin site.
But it seems the pimcore cannot detect the assets and controller from this bundle

Here i provide the screenshot  : 
![image](https://user-images.githubusercontent.com/28853391/35716160-7c2aba6c-0809-11e8-97ce-fa69b53b5d94.png)

![image](https://user-images.githubusercontent.com/28853391/35716174-8d82645e-0809-11e8-9ddc-5375dcfea626.png)

I'm using PIMCORE 5.1.2, do i have miss something when install it ?

Thanks

**Comment by dpfaffenbauer** [comment]
could you try running ```bin/console assets:install```?

**Comment by kiky-salt** [comment]
@dpfaffenbauer yes, already found that the issue since i run it on windows

many thanks for your support

**Comment by dpfaffenbauer** [comment]
you are welcome :)
